name: ci
on: push

env:
  NODE_VERSION: 18.6.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: last-run
        uses: nonrational/sha-storage-action@master
        with:
          result: success
